"""primeira criação de tabelas na bd

Revision ID: 17375436a569
Revises: 
Create Date: 2025-09-21 13:36:32.359131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17375436a569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_table('disciplina',
    sa.Column('id_disci', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_disci')
    )
    op.create_table('escola',
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('endereco', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_escola'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disciplina_curso',
    sa.Column('id_disci', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.ForeignKeyConstraint(['id_disci'], ['disciplina.id_disci'], ),
    sa.PrimaryKeyConstraint('id_disci', 'id_curso')
    )
    op.create_table('professor',
    sa.Column('id_prof', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id_escola'], ),
    sa.PrimaryKeyConstraint('id_prof'),
    sa.UniqueConstraint('email')
    )
    op.create_table('responsavel',
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id_escola'], ),
    sa.PrimaryKeyConstraint('id_responsavel'),
    sa.UniqueConstraint('email')
    )
    op.create_table('turma',
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('ano_classe', sa.String(length=20), nullable=False),
    sa.Column('sala', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('ano_lectivo', sa.String(length=20), nullable=False),
    sa.Column('limite_alunos', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id_escola'], ),
    sa.PrimaryKeyConstraint('id_turma')
    )
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('num_matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id_escola'], ),
    sa.ForeignKeyConstraint(['id_turma'], ['turma.id_turma'], ),
    sa.PrimaryKeyConstraint('id_aluno'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_matricula')
    )
    op.create_table('disciplina_professor',
    sa.Column('id_disci', sa.Integer(), nullable=False),
    sa.Column('id_prof', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_disci'], ['disciplina.id_disci'], ),
    sa.ForeignKeyConstraint(['id_prof'], ['professor.id_prof'], ),
    sa.PrimaryKeyConstraint('id_disci', 'id_prof')
    )
    op.create_table('disciplina_turma',
    sa.Column('id_disci', sa.Integer(), nullable=False),
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_disci'], ['disciplina.id_disci'], ),
    sa.ForeignKeyConstraint(['id_turma'], ['turma.id_turma'], ),
    sa.PrimaryKeyConstraint('id_disci', 'id_turma')
    )
    op.create_table('formulario_avaliacao',
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('topico1', sa.String(length=40), nullable=True),
    sa.Column('topico2', sa.String(length=40), nullable=True),
    sa.Column('topico3', sa.String(length=40), nullable=True),
    sa.Column('topico4', sa.String(length=40), nullable=True),
    sa.Column('topico5', sa.String(length=40), nullable=True),
    sa.Column('topico6', sa.String(length=40), nullable=True),
    sa.Column('topico7', sa.String(length=40), nullable=True),
    sa.Column('topico8', sa.String(length=40), nullable=True),
    sa.Column('topico9', sa.String(length=40), nullable=True),
    sa.Column('topico10', sa.String(length=40), nullable=True),
    sa.Column('topico11', sa.String(length=40), nullable=True),
    sa.Column('topico12', sa.String(length=40), nullable=True),
    sa.Column('topico13', sa.String(length=40), nullable=True),
    sa.Column('topico14', sa.String(length=40), nullable=True),
    sa.Column('topico15', sa.String(length=40), nullable=True),
    sa.Column('topico16', sa.String(length=40), nullable=True),
    sa.Column('topico17', sa.String(length=40), nullable=True),
    sa.Column('topico18', sa.String(length=40), nullable=True),
    sa.Column('topico19', sa.String(length=40), nullable=True),
    sa.Column('topico20', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.String(length=40), nullable=True),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_responsavel'], ['responsavel.id_responsavel'], ),
    sa.PrimaryKeyConstraint('id_form')
    )
    op.create_table('avaliacao_outros',
    sa.Column('id_av', sa.Integer(), nullable=False),
    sa.Column('nota_topico1', sa.Integer(), nullable=True),
    sa.Column('nota_topico2', sa.Integer(), nullable=True),
    sa.Column('nota_topico3', sa.Integer(), nullable=True),
    sa.Column('nota_topico4', sa.Integer(), nullable=True),
    sa.Column('nota_topico5', sa.Integer(), nullable=True),
    sa.Column('nota_topico6', sa.Integer(), nullable=True),
    sa.Column('nota_topico7', sa.Integer(), nullable=True),
    sa.Column('nota_topico8', sa.Integer(), nullable=True),
    sa.Column('nota_topico9', sa.Integer(), nullable=True),
    sa.Column('nota_topico10', sa.Integer(), nullable=True),
    sa.Column('nota_topico11', sa.Integer(), nullable=True),
    sa.Column('nota_topico12', sa.Integer(), nullable=True),
    sa.Column('nota_topico13', sa.Integer(), nullable=True),
    sa.Column('nota_topico14', sa.Integer(), nullable=True),
    sa.Column('nota_topico15', sa.Integer(), nullable=True),
    sa.Column('nota_topico16', sa.Integer(), nullable=True),
    sa.Column('nota_topico17', sa.Integer(), nullable=True),
    sa.Column('nota_topico18', sa.Integer(), nullable=True),
    sa.Column('nota_topico19', sa.Integer(), nullable=True),
    sa.Column('nota_topico20', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=100), nullable=True),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_form'], ['formulario_avaliacao.id_form'], ),
    sa.PrimaryKeyConstraint('id_av')
    )
    op.create_table('avaliacao_prof',
    sa.Column('id_av', sa.Integer(), nullable=False),
    sa.Column('nota_topico1', sa.Integer(), nullable=True),
    sa.Column('nota_topico2', sa.Integer(), nullable=True),
    sa.Column('nota_topico3', sa.Integer(), nullable=True),
    sa.Column('nota_topico4', sa.Integer(), nullable=True),
    sa.Column('nota_topico5', sa.Integer(), nullable=True),
    sa.Column('nota_topico6', sa.Integer(), nullable=True),
    sa.Column('nota_topico7', sa.Integer(), nullable=True),
    sa.Column('nota_topico8', sa.Integer(), nullable=True),
    sa.Column('nota_topico9', sa.Integer(), nullable=True),
    sa.Column('nota_topico10', sa.Integer(), nullable=True),
    sa.Column('nota_topico11', sa.Integer(), nullable=True),
    sa.Column('nota_topico12', sa.Integer(), nullable=True),
    sa.Column('nota_topico13', sa.Integer(), nullable=True),
    sa.Column('nota_topico14', sa.Integer(), nullable=True),
    sa.Column('nota_topico15', sa.Integer(), nullable=True),
    sa.Column('nota_topico16', sa.Integer(), nullable=True),
    sa.Column('nota_topico17', sa.Integer(), nullable=True),
    sa.Column('nota_topico18', sa.Integer(), nullable=True),
    sa.Column('nota_topico19', sa.Integer(), nullable=True),
    sa.Column('nota_topico20', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=100), nullable=True),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_form'], ['formulario_avaliacao.id_form'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id_prof'], ),
    sa.PrimaryKeyConstraint('id_av')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao_prof')
    op.drop_table('avaliacao_outros')
    op.drop_table('formulario_avaliacao')
    op.drop_table('disciplina_turma')
    op.drop_table('disciplina_professor')
    op.drop_table('aluno')
    op.drop_table('turma')
    op.drop_table('responsavel')
    op.drop_table('professor')
    op.drop_table('disciplina_curso')
    op.drop_table('escola')
    op.drop_table('disciplina')
    op.drop_table('curso')
    # ### end Alembic commands ###
